#!/usr/bin/bash


docker run -d --name jenkins \
    --user root \
    -p 8080:8080 -p 50000:50000 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v jenkins_home:/var/jenkins_home \
    jenkins/jenkins:lts

#docker pull jenkins/jenkins
#docker run -d --name jenkins -p 80:8080 jenkins/jenkins
#sleep 10 && docker exec jenkins sh -c 'cat /var/jenkins_home/secrets/initialAdminPassword'
